Página de login
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #1
Opened 2020-10-26 03:06 UTC by GabrielDVpereira

## Descrição

Criação da página de login para a nossa aplicação

## Issues 
[#159](https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/159)

## Tasks
* Criação da tela de login
* Configuração do docker para comunicação com  o backend 
* Configuração das rotas da aplicação
* Criação do fluxo de login pelo context da aplicação 

## Prs relacionados
[#13](https://github.com/UnBArqDsw/2020.1_G12_Stock_Backend/pull/13)  

## Checklist
- [x] Tela responsiva para todos os devices

![image](https://user-images.githubusercontent.com/37307099/97129992-fb72e200-171e-11eb-85cb-835e5ef42131.png)
![image](https://user-images.githubusercontent.com/37307099/97130030-10e80c00-171f-11eb-9ae8-d1004cfc32ed.png)

2020-10-26 15:21 UTC, micaellagouveia requested changes

2020-10-26 15:21 UTC, micaellagouveia commented on src/Pages/AuthPages/Login/index.js
> +          <label htmlFor="password">SENHA:</label>
O nome SENHA não precisa estar em capslock

2020-10-26 15:21 UTC, micaellagouveia commented on src/Pages/AuthPages/Login/index.js
> +          <input onChange={(e) => setPassword(e.target.value)} id="password" />
A senha está aparecendo quando digita, só mudar o tipo do input

2020-10-26 15:22 UTC, micaellagouveia commented
Ficou lindo demais arrasou mtttt

2020-10-27 00:05 UTC, pedroeagle approved these changes
Muito boom!

2020-10-27 01:18 UTC, micaellagouveia approved these changes

2020-10-27 01:19 UTC, merged