196 nivel colaborador
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #10
Opened 2020-11-11 00:21 UTC by sofiapatrocinio

Adição da funcionalidade de editar colaborador:
![Peek 2020-11-10 21-06](https://user-images.githubusercontent.com/38709421/98749421-66b4e900-239a-11eb-9de4-b604a5783fc2.gif)

Adição da função de busca:
![Peek 2020-11-10 21-16](https://user-images.githubusercontent.com/38709421/98749407-60bf0800-239a-11eb-9be9-c13f5787bbcc.gif)

Issue #196 https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/196

2020-11-12 20:29 UTC, pedroeagle approved these changes

2020-11-13 17:18 UTC, GabrielDVpereira requested changes

2020-11-13 17:18 UTC, GabrielDVpereira commented on src/Components/Modals/UpdateCollaboratorModal/index.js
> +    if (idAccessLevel) nameAccessLevel();
aqui o useEffect está com o array de efeito vazio, isso significa que ele só vai executar uma vez. Com isso, como o idAccessLevel é uma variável de estado que começa com ' ', possivelmente esse nameAccessLevel não é chamado.

2020-11-13 17:18 UTC, GabrielDVpereira commented on src/Pages/Collaborators/index.js
>      if (user) loadCollaborators();
colocar o user no array de efeito do userEffect

2020-11-13 17:18 UTC, GabrielDVpereira commented on src/Components/Modals/UpdateCollaboratorModal/index.js
> +    if (idAccessLevel) nameAccessLevel();
Aq nesse caso, eu recomendo ficar o useEffect separado para o nameAccessLevel com esse mesmo if e com o idAccessLevel no array de efeito.

2020-11-13 17:18 UTC, GabrielDVpereira commented on src/Pages/Collaborators/index.js
> +    const collaboratorsFilteredBySearch = collaborators.filter((product) => product.name.includes(search));
trocar product no filtro por collaborator

2020-11-13 17:29 UTC, GabrielDVpereira approved these changes

2020-11-13 17:29 UTC, GabrielDVpereira commented on src/Components/Modals/UpdateCollaboratorModal/index.js
> +    if (idAccessLevel) nameAccessLevel();
tbm vi que chamam o nameAccessLevel no getCollaborator, ai n precisa chamar o nameAccessLevel aqui dentro do UseEffect.

2020-11-13 17:30 UTC, GabrielDVpereira requested changes
Só fazer esses ajustes :)

2020-11-13 18:57 UTC, GabrielDVpereira approved these changes

2020-11-13 18:58 UTC, merged