194 Dar baixa em produtos e remover itens por defeito
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #11
Opened 2020-11-13 13:30 UTC by pedroeagle

# Descrição do que foi feito
Foram criados os botões para baixa de produto além de um modal para remoção de um produto de um lote específico. Não consegui organizar os botões para ficarem no local correto pelo style, logo peço que se alguém puder me ajude nisso.

# Resolve [194](https://github.com/UnBArqDsw/2020.1_G12_Stock/issues/194)

2020-11-14 15:53 UTC, sofiapatrocinio requested changes
![image](https://user-images.githubusercontent.com/38709421/99151217-4f1a8080-2678-11eb-9299-40a412c8cc57.png)

Aqui tem que bloquear números menores que 0

2020-11-15 17:57 UTC, GabrielDVpereira commented
O pr estava com muitos conflitos e a lógica para dar baixa em um produto está um pouco dificil de entender. Antes de terminar o review dele eu vou terminar a parte de socket para não atrasar ainda mais. Talvez seja melhor refatorar essa parte de deleção de produto dps que o socket estiver pronto, eu me disponibilizo pra isso, mas vou precisar que me explique algumas coisas do pr

2020-11-18 14:41 UTC, micaellagouveia approved these changes

2020-11-18 20:05 UTC, sofiapatrocinio requested changes
O padrão do alerta é o modal de result 
![Screenshot from 2020-11-18 17-01-29](https://user-images.githubusercontent.com/38709421/99581707-e278ec00-29bf-11eb-9203-0ff7c9675215.png)

Não tem como eu saber qual a quantidade de produtos, deveria mostrar. Tentei decrementar um produto que não possuia quantidade e precisei abrir o insomnia pra saber, o usuário não tem acesso a isso.

O modal de confirmação tá com os botões de sim e não da mesma cor e vermelho, deve seguir o padrão dos demais. 

Não deve ser possível decrementar 0 unidade. Sempre retorna erro.

2020-11-20 00:16 UTC, sofiapatrocinio approved these changes

2020-11-20 00:16 UTC, merged