Update readme
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #2
Opened 2020-10-26 15:36 UTC by micaellagouveia

Atualização do README do front

2020-10-26 23:29 UTC, pedroeagle requested changes
Acho que você commitou os arquivos *-lock.json sem querer

2020-10-27 00:33 UTC, pedroeagle requested changes
O package-lock.json ainda está no PR

2020-10-27 00:42 UTC, pedroeagle requested changes
O package-lock.json ainda está no PR

2020-10-27 00:52 UTC, pedroeagle approved these changes

2020-10-27 00:53 UTC, sofiapatrocinio approved these changes

2020-10-27 00:53 UTC, merged