187 add colaborador
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #8
Opened 2020-11-07 21:46 UTC by micaellagouveia

Adição da página de colaboradores, possuindo as funções de cadastrar novo colaborador, ativar/desativar colaborador

Issue #6 

Responsivo para web e mobile:
![desktop](https://user-images.githubusercontent.com/48630408/98451928-62ce6000-2129-11eb-9612-ac931a89020a.png)
![mobile](https://user-images.githubusercontent.com/48630408/98451929-63ff8d00-2129-11eb-89e0-4736809440d0.png)

2020-11-08 18:30 UTC, pedroeagle approved these changes

2020-11-08 18:42 UTC, pedroeagle requested changes

2020-11-08 18:42 UTC, pedroeagle commented on src/Pages/Collaborators/index.js
> +  const nameAccessLevel = (user) => {
esse switch case aqui era pra estar no back, é pra isso que temos o atributo description na tabela access level. era só solicitar ao back qual é a descrição do access level de id 'n'.

2020-11-09 17:15 UTC, GabrielDVpereira approved these changes
Concordo com o Igor, tirando isso está tudo bom. Mto mto bem.

2020-11-09 21:26 UTC, pedroeagle approved these changes
Muito boom!

2020-11-09 21:45 UTC, merged