188 cadastro produto
UnBArqDsw/2020.1_G12_Stock_Frontend pull request #9
Opened 2020-11-08 18:51 UTC by pedroeagle

Criação da tela de estoque, modais da criação de produto, lote e categorias.

2020-11-09 23:56 UTC, sofiapatrocinio commented
Ficou muito bom! Acho que podemos fazer algumas mudanças só pra deixar o caminho do usuário melhor.

No campo de preço acho que poderia ter um texto fixo com um "R$ ...." e o que o usuário preencher, pra não ficar um valor solto
![image](https://user-images.githubusercontent.com/38709421/98609009-2dfa0e80-22cb-11eb-98ef-2dc984b6da70.png)

Aqui, acho que faz mais sentido primeiro vir quantidade, depois unidade de medida, por ser a forma como normalmente escrevemos em tabelas por exemplo
![image](https://user-images.githubusercontent.com/38709421/98609095-584bcc00-22cb-11eb-8c36-56b87b368f6d.png)

Eu redesenhei essa parte de categorias, mas se der muito trabalho pra implementar é só uma ideia haha 
![image](https://user-images.githubusercontent.com/38709421/98609775-e07ea100-22cc-11eb-858e-21568a3bc791.png)
Os pontos que quero levantar são:

- O botão vermelho chama atenção e acho que deve ser usado pra ações destrutivas
- Acho melhor deixar o modal com um botão de ação só embaixo, pra não confundir o usuário


![image](https://user-images.githubusercontent.com/38709421/98609908-318e9500-22cd-11eb-8f10-b0bbeb0116d8.png)

- Aqui acho que não precisa ter data de entrada, acho que devemos pegar essa data de acordo com o dia que o usuário tá executando a ação

- Preço de compra a mesma coisa do preço no modal de adicionar produto 

- Falta placeholder nos campos pra melhor explicação, principalmente quantidade

E por último: descrição precisa mesmo ser obrigatório em lote e categoria?

2020-11-09 23:57 UTC, sofiapatrocinio commented
Ah, o modal de resultado já está na master. É bom padronizar
![image](https://user-images.githubusercontent.com/38709421/98610347-212aea00-22ce-11eb-9068-01c5fb8b50e9.png)

2020-11-10 00:08 UTC, sofiapatrocinio requested changes

2020-11-10 00:08 UTC, sofiapatrocinio commented on src/Pages/AuthPages/Login/index.js
> +    console.log(document, password);
Retirar console.log

2020-11-10 03:21 UTC, GabrielDVpereira commented
@sofiapatrocinio realizei algumas alterações que foram pedidas. Porém, acho que devido a necessidade de pressa no desenvolvimento de funções principais de nosso app, é melhor deixar a refatoração da categoria para outro momento e apenas trocar a cor do botão de criar categoria, como fiz.

2020-11-10 13:09 UTC, pedroeagle commented
@sofiapatrocinio 
sobre a data de entrada ser solicitada: há a possibilidade de eu registrar na segunda-feira um estoque que chegou pós horário de expediente na sexta, logo a data de entrada do lote deveria ser na segunda pra ser mais coerente com a informação real.
lote precisa de descrição porque é uma das únicas formas do usuário diferenciar os lotes e saber de qual remover um produto com defeito, por exemplo.

2020-11-10 13:11 UTC, pedroeagle commented
![image](https://user-images.githubusercontent.com/45996980/98678273-0f346000-233d-11eb-965e-3a4e79017a96.png)
um exemplo de como estou utilizando a descrição do lote em outra issue

2020-11-10 20:13 UTC, micaellagouveia approved these changes
Excelenteeee, so as páginas que não estao recarregando automaticamente, mas isso será resolvido na próxima issue :) Showw

2020-11-10 21:13 UTC, sofiapatrocinio requested changes
![image](https://user-images.githubusercontent.com/38709421/98733942-10d34780-2380-11eb-8403-b0f747c77456.png)
O botão de criar categoria ainda tá vermelho

![image](https://user-images.githubusercontent.com/38709421/98734021-2b0d2580-2380-11eb-844b-1e143c6035d5.png)
O modal ainda não tá padronizado

![image](https://user-images.githubusercontent.com/38709421/98734090-3eb88c00-2380-11eb-946b-9d96a0970ed6.png)

- A data de entrada poderia pelo menos ficar default com a data atual, pra o usuário não precisar preencher tantos campos

- E o campo de preço não tá com R$

2020-11-11 18:22 UTC, sofiapatrocinio approved these changes

2020-11-11 18:22 UTC, merged